---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте 
  - Пользователь должен иметь возможность востановить пароль
  - Имя пользователя должно начинаться только с латинской буквы и содержать в себе от 3 до 16 символов, латинские буквы, цифры и подчеркивания
  - Поля Email, Password и Password Confirmation не могут быть пустыми
  - Пароль должен содержать в себе от 6 до 16 символов
  - Должна выполняться валидация введенного адреса эл. почты
  - Должна выполняться проверка имени пользователя на уникальность
  - Пользователь должен иметь возможость зарегистрироваться с помощью профиля GitHub и Discord
  - Пользователь должен иметь возможность начать пробную игру без регистрации на сайте
  - После авторизации пользователь автоматически должен попадать на главную страницу
  - Главная страница должна содерждать в себе хидер и футер, а также блоки лобби, список турниров, история, таблица лидеров, чат, кнопка создания новой игры
  - Хидер должен содержать логотип сайта, количество онлайн игроков, уведомления о приглашениях в игры и кнопку профиля пользователя
  - Футер должнен содрежать информацию о компании, версию сайта и данные о посещаемости
  - Раздел Лобби должен содерждать список текущих игр и приглашений в игру другими пользователями
  - Раздел Турниры должен содерждать таблицу с информцией о текущих и завершенных играх, с возможностью присоединиться в качестве зрителя
  - Раздел История должен содерждать таблицу со всеми завершенными играми
  - Таблица лидеров должна содерждать таблицу с рейтингом пользователей с разделеним на неделю, месяц, все время
  - В чате у пользователя должна быть возможность отправить сообщение в общий чат или только одному игроку, который находится онлайн
  - В блоке чата должен находиться список игроков, которые находятся в онлайне 
  - После нажатия кнопки Create a game должно открываться вплывающее окно создания новой игры с выбором сложности игры (1-4 уровень), типа игры (с пользователем, с другом или с ботом), лимита времени (от 3 до 60 минут) и задачи (рандомная игра, выбор из списка по названию или тегам)
  - В разделе My profile должны отображатьcя аватарка, имя, выбранный язык программирования, дата регистрации, статистика и активность, а также список завершенных игр
  - В разделе Settings пользователь должен иметь возможность изменить имя, язык программирования, свой клан, а также выбрать тип звука и громкость
  - В разделе Users rating должен находиться рейтинг всех пользователей с возможностью фильтрации и сортировки
  - В разделе Tasks должны находиться все созданные пользователями задачи. Есть возможность содания новой
  - В разделе Tournaments должны отобращаться текущие и завершенные турниры. Есть возможность создания нового
  - В меню пользователя должны находиться разделы SourceCode, Hexlet, Join Discord, Tg#codebattle, по нажатию на которые должны открываться страницу проекта в Github, страницу сайта Hexlet, ссылки на присоединение к общему чату Discord и Telegram соответственно
  - На странице игры должны отображаться раздел с задачей и примером, чат, поле для ввода кода, а также поле, в котором отображается код соперника
  - Пользователь жолжен иметь возможность изменить язык задачи (русский/английский)
  - Во время игры должен отображаться таймер оставшегося времени
  - Во время игры у игрока есть воможность изменить язык программирования
  - После нажатия на кнопку Show guide дложно открываться обучающее окно, показывающее основные функции поля и кнопки страницы
  - Во время игры должна быть доступна кнопка для проверки решения. В случае, если решение верное игра завершается победой игрока
  - Во время игры должна быть доступна кнопка для возможности сдаться. В случае её нажатия игра заканчивается поражением игрока
  - По завершению игры обоим игрокам должно показывается окно, в котором выходит сообщение о проигрыше или победе, в зависимости от исхода игры
  - По завершению игры у игроков должна быть возможность сыграть эту же игру повторно либо вернуться на главную страницу
  - У пользователей должна быть возможность присоединиться к игре в качестве зрителя

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  
implicit:
  - Должна быть возможность командной игры (например, 2 на 2). Для общения между игроками одной команды - голосовой чат, либо возможность писать комментарии к коду твоего сокомандника
  - Должна быть возможность создания приватной игры (доступ только по ссылке, либо по паролю/коду)
  - Должна быть возможность добавления в друзья другого пользователя, соответственно должна быть воможность посмотра своего рейтинга среди друзей, истории игр твоих друзей и т.д
