---
functional:
  - требование 1
  - требование 2

  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте 
  - Пользователь должен иметь возможность востановить пароль
  - Имя пользователя должно начинаться только с латинской буквы и содержать в себе от 3 до 16 символов, латинские буквы, цифры и подчеркивания
  - Поля 'Email', 'Password' и 'Password Confirmation' не могут быть пустыми
  - Пароль должен содержать в себе от 6 до 16 символов
  - Должна выполняться валидация введенного адреса эл. почты
  - Должна выполняться проверка имени пользователя на уникальность
  - Пароль введенный в поля 'Password' и 'Password Confirmation' должен совпадать
  - Пользователь должен иметь возможость зарегистрироваться с помощью профиля GitHub и Discord
  - Пользователь доджен иметь возможность начать пробную игру без регистрации на сайте
  
  




non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6
