---
functional:
  - требование 1
  - требование 2

  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте 
  - Пользователь должен иметь возможность востановить пароль
  - Имя пользователя должно начинаться только с латинской буквы и содержать в себе от 3 до 16 символов, латинские буквы, цифры и подчеркивания
  - Поля 'Email', 'Password' и 'Password Confirmation' не могут быть пустыми
  - Пароль должен содержать в себе от 6 до 16 символов
  - Должна выполняться валидация введенного адреса эл. почты
  - Должна выполняться проверка имени пользователя на уникальность
  - Пароль введенный в поля 'Password' и 'Password Confirmation' должен совпадать
  - Пользователь должен иметь возможость зарегистрироваться с помощью профиля GitHub и Discord
  - Пользователь доджен иметь возможность начать пробную игру без регистрации на сайте
  - После авторизации пользователь автоматически должен попадать на главную страницу
  - Главная страница должна содерждать в себе хидер и футер, а также блоки лобби, список турниров, история, таблица лидеров, чат, кнопка создания новой игры
  - Раздел Лобби (Lobby) содержит таблицу текущих игр и приглашений в игру другими пользователями
  - Раздел Турниры (Tournaments) содержит таблицу с информцией о текущих и завершенных играх, с возможность присоединиться в качестве зрителя
  - Раздел История (History) содержит таблицу со всеми завершенными играми
  - Таблица лидеров (Ledearboard) содержит в таблицу с рейтингом пользователей с разделеним на неделю, месяц, все время
  

  




non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6
